// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsbeHJcRrMtwrxDCGwABqmlrYDTG5f3uU',
    appId: '1:956150016335:android:0e556d9ac22e81bdbdfd3a',
    messagingSenderId: '956150016335',
    projectId: 'helping-pets-and-me',
    databaseURL: 'https://helping-pets-and-me-default-rtdb.firebaseio.com',
    storageBucket: 'helping-pets-and-me.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgCru8vOGJKLgtHyOLekI2hRgX15bmqjw',
    appId: '1:956150016335:ios:55ad706b15810952bdfd3a',
    messagingSenderId: '956150016335',
    projectId: 'helping-pets-and-me',
    databaseURL: 'https://helping-pets-and-me-default-rtdb.firebaseio.com',
    storageBucket: 'helping-pets-and-me.appspot.com',
    androidClientId: '956150016335-8tie7453t058ufgk4m9jm0hculupc748.apps.googleusercontent.com',
    iosClientId: '956150016335-ke35q9u04kp8v8t84b9bsm07f4nfpk6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.animalApp',
  );
}
